version: "3"
#MYSQL
services:
  database:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockcommerce
      MYSQL_USER: usuario
      MYSQL_PASSWORD: root
    volumes:
      - stockcommerceDB:/var/lib/mysql

  #FLASK APP
  web:
    build: ./backend #busca el archivo app.py en la carpeta backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app

volumes:
  stockcommerceDB:
