#MYSQL

services:
  database:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockcommerce
      MYSQL_USER: usuario
      MYSQL_PASSWORD: root
    volumes:
      - stockcommerceDB:/var/lib/mysql

  #PYTHON APP
  web:
    build: .
    ports:
      - "5000:5000"

volumes:
  stockcommerceDB:
